# AppVeyor uses this file in preference to their web-based configuration.
#
# Reference documents:
#
#  * appveyor.yml reference: http://www.appveyor.com/docs/appveyor-yml
#  * build pipeline described here: http://www.appveyor.com/docs/build-configuration
#  * environment vars: http://www.appveyor.com/docs/environment-variables

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.3.{build}

branches:
  # whitelist
  only:
    - appveyor
    - master
    - develop
    - develop-v2

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
clone_folder: c:\projects\catch

# fetch repository as zip archive
shallow_clone: true


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
# NB: Workaround: Use platform:"Any CPU" to build x86 because
# platform: x86 will cause MSBuild to try to build the solution's "x86" target,
# but CMake doesn't create an 'x86' target, it creates a "Win32" target.
platform:
  - Any CPU
  - x64

# build Configuration, i.e. Debug, Release, etc.
configuration:
  - Debug
  - Release

# environment variables
environment:
  matrix:
  - platform: Any CPU
    my_cmake_arch: Win32
  - platform: x64
    my_cmake_arch: x64

# scripts to run before build
# NB: let cmake auto-detect the MSVS version, but specify an arch with -A
before_build:
  - echo Running cmake...
  - cd c:\projects\catch
  - cmake -Hprojects/CMake -BBuild -A%my_cmake_arch%
  
# build with MSBuild
build:
  parallel: true                # enable MSBuild parallel builds
  project: Build\Catch.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal             # quiet|minimal|normal|detailed

  
test_script:
  - cd Build
  - ctest -V -j 1 -C %CONFIGURATION%
  